import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "SonicAI — AI-Powered Headphone Shopping",
  description: "Discover your perfect headphones through conversational AI. Premium recommendations, intelligent comparisons, and a seamless shopping experience.",
  keywords: ["headphones", "AI shopping", "noise cancelling", "wireless headphones", "earbuds"],
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 5e57dcded12b3da2eac7a0dc119166de4fefaf62
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="h-full font-sans bg-gray-50/30">{children}</body>
=======
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
>>>>>>> 5e57dcded12b3da2eac7a0dc119166de4fefaf62
    </html>
  );
}
